# Configurações do Banco de Dados H2 (em memória)
spring.datasource.url=jdbc:h2:mem:crud-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Configurações do Servidor
server.port=8080

# Configurações do Console H2 (permite ver o banco no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console